os: osx

language: go

env:
  global:
    - TEST_ON_MACOSX=true
    - MACHINE_NAME="eris-test-osx-$TRAVIS_BUILD_ID"
matrix:
  allow_failures:
    #Native Docker job, expect potential failures as it's still fresh
    - env:
        - DOCKER_NATIVE=true
  include:
    #Docker machine job, expect this to pass
    - go: 1.7.3
      env:
        - DOCKER_MACHINE=true
      after_script: 
        - tests/dm_cleanup.sh
        #Native Docker job, expect potential failures as it's still fresh
    - go: 1.7.3
      env:
        - DOCKER_NATIVE=true


install:
  - brew update
  - brew install jq
  - brew install caskroom/cask/brew-cask
  - test "$DOCKER_MACHINE" = true && brew install docker docker-machine || brew cask install docker
  - docker --version
  - go install ./cmd/eris

script:
  - ./tests/test.sh

notifications:
  email: false
  slack:
    secure: QExEkkFtFt7BdtDeAiWOQxtQqyoBbWrBpfgcYU+pdpABC/bRv2TFyjzqKnxM479Hc30qUvzM6FCijc/qjDvEeDy9KMyiCR7HgtFy6T0Ixz/37kfMbTbxmAIxVPsBjVLtjDsnIL7RlJDNqEs1H5ZUdeBFm8+kh3FIiZQC5d9Bk+oQqk+7RZYmAm/VnA01NtV2UpxaP6Be4zryul2span3F3TPbh3ltgaCK7rC0dt2RMmr8w3IAdD4UvyUZueTzIp+lOm3lX6ldZQ5JuxZySarsnyPbTvMiRpcBRpC9JpCH9DUoREuDO008W7Zh7kLCx0J59iyD94B7xDen4wP8p2zzGaUSIvMRYihBNdbBz/rb/UiutNC5B0PgcaUw0t7IUprNsPifSUwk/VgOFrAPsvcpuLQ0JuN3xaQvojoHfwT/b2ks2ioOTzlC0NPDnxXz/qrXU2qsKfQGQXUNpVOCEor0UKYoMilZA2+vO+/62uD2sC2u2d/SGtqyu/EomsoRg+AGJMQPUqNpeeu/+PkbBV1pGsZuXTao0Bu+1GgrBg8Y9azQkOGfH2sK8iJzWLv2TMVeMCtAO+KKICKSISQiEX8SfjDTRhIg5h2ts6q2qBNtnFyBwO2Ah7S5TcdjXspB1oJ+lY/Tr/1n9ahrgq9utDSFUQPDG9EdcHQkiNgItrot8U=