version: "{build}-{branch}"
os: Visual Studio 2015
# Source Config
clone_folder: C:\gopath\src\github.com\eris-ltd\eris

environment:
  global:
    TEST_ON_WINDOWS: "true"
    GOPATH: C:\gopath
    GOBIN: C:\gopath\bin
    CC: gcc.exe
    PATH: '%PATH%;C:\gopath\bin;C:\msys64\mingw64\bin\;C:\Program Files (x86)\NSIS\;'
    MSYS2_ARCH: x86_64
    MSYS2_BITS: 64
    MSYSTEM: MINGW64
  matrix:
  - DOCKER_MACHINE: "true"
    MACHINE_NAME: 'eris-test-win-%APPVEYOR_BUILD_ID%'
    DOCKER_VERSION: 1.10.0
    DOCKER_MACHINE_VERSION: 0.4.1
    AWS_ACCESS_KEY_ID:
      secure: qHdpZ2qgqg7LcbD1GJJ5JHPZJ1Bn0dQ8LoXgZpKrXBQ=
    AWS_SECRET_ACCESS_KEY:
      secure: SM1ZHeoInEuFq7Crxwsvq+9ukaCpR4lFBoPGRMTUIOOPmzCwOU6nTqO+NFW1DnQO
    AWS_DEFAULT_REGION: eu-west-1
    AWS_VPC_ID:
      secure: Lo717dojMJUNytpQPZWwyw==
    AWS_SECURITY_GROUP:
      secure: Jie7WuAzjiHVp7tX8MfaSQ==
  - allow_failures:
    DOCKER_NATIVE: "true"



install:
  - gcc --version
  - choco upgrade golang
  - cinst cygwin
  - cinst jq
  - ps: >-
      If ($env:DOCKER_MACHINE -eq "true") {
        cinst docker --version $env:DOCKER_VERSION; cinst docker-machine --version $env:DOCKER_MACHINE_VERSION
      } Else {
        cinst docker-for-windows
      }

build_script:
- cmd: >-

    cd c:\gopath\src\github.com\eris-ltd\eris

    go install .\cmd\eris

after_test:
  - bash c:\gopath\src\github.com\eris-ltd\eris\tests\dm_cleanup.sh

test_script:
- cmd: >-

    bash c:\gopath\src\github.com\eris-ltd\eris\tests\test.sh
